apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-nextjs
          image: albiert/todo-app:latest
          ports:
            - containerPort: 3000
              name: todo
          env:
            - name: SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: SERVER_URL # the value of the variable comes from 1.2

