apiVersion: v1
kind: Service
metadata:
  name: todo-svc
  namespace: todo-app
  labels:
    app: todo-app
spec:
  type: NodePort
  ports:
    - name: todo-svc
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: todo-app
